; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{060BAF13-F913-47D2-99A1-5504676249BA}
AppName=Ruffle
AppVersion=0.3.0
;AppVerName=Ruffle 0.3.0
AppPublisher=� 2026 Ruffle Team
AppPublisherURL=https://ruffle.rs/
AppSupportURL=https://ruffle.rs/
AppUpdatesURL=https://ruffle.rs/
DefaultDirName={pf64}\Ruffle
DefaultGroupName=Ruffle
AllowNoIcons=yes
LicenseFile=D:\Programación\Windows\Apps\Ruffle\3.0\ruffle-0.3.0-windows-x86_64\docs\LICENSE.md
OutputDir=D:\Programación\Apps\Win\Apps\Ruffle\3.0
OutputBaseFilename=ruffle-0.3.0-windows-x86_64
SetupIconFile=D:\Programación\Windows\Apps\Ruffle\3.0\ruffle-0.3.0-windows-x86_64\icons\favicon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "armenian"; MessagesFile: "compiler:Languages\Armenian.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "catalan"; MessagesFile: "compiler:Languages\Catalan.isl"
Name: "corsican"; MessagesFile: "compiler:Languages\Corsican.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "norwegian"; MessagesFile: "compiler:Languages\Norwegian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "tamil"; MessagesFile: "compiler:Languages\Tamil.isl"
Name: "thai"; MessagesFile: "compiler:Languages\Thai.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\Programación\Windows\Apps\Ruffle\3.0\ruffle-0.3.0-windows-x86_64\bin\ruffle.exe"; DestDir: "{app}/bin"; Flags: ignoreversion
Source: "ruffle-0.3.0-windows-x86_64\icons\favicon.ico"; DestDir: "{app}\icons"; Flags: ignoreversion
Source: "ruffle-0.3.0-windows-x86_64\docs\LICENSE.md"; DestDir: "{app}\docs"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Ruffle"; Filename: "{app}\bin\ruffle.exe"; IconFilename: "{app}\icons\favicon.ico"; IconIndex: 0; Comment: "A Flash Player emulator written in Rust"
Name: "{group}\{cm:ProgramOnTheWeb,Ruffle}"; Filename: "https://ruffle.rs/"
Name: "{group}\{cm:UninstallProgram,Ruffle}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Ruffle"; Filename: "{app}\bin\ruffle.exe"; IconFilename: "{app}\icons\favicon.ico"; IconIndex: 0; Comment: "A Flash Player emulator written in Rust"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Ruffle"; Filename: "{app}\bin\ruffle.exe"; IconFilename: "{app}\icons\favicon.ico"; IconIndex: 0; Comment: "A Flash Player emulator written in Rust"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\bin\ruffle.exe"; Description: "{cm:LaunchProgram,Ruffle}"; Flags: nowait postinstall skipifsilent
